#!/bin/bash

kernel=$(uname -r)
cpu=$(lscpu | awk '/^Model name/ {for (i=3; i<=NF; i++) printf "%s%s", $i, (i<NF ? " " : "\n")}')
ram_total=$(free -h | awk '/^Mem/ {print $2}')
ram_used=$(free -h | awk '/^Mem/ {print $3}')


echo "Your hostname is : $HOSTNAME
Operating System : $OSTYPE
Kernel 		 : $kernel
CPU Name	 : $cpu	
Memory Total	 : $ram_total
Memory Used	 : $ram_used"
