#!/bin/bash

  source /etc/os-release

  kernel=$(uname -r)
  cpu=$(LC_ALL=C lscpu | awk -F: '/^Model name:/ {
      sub(/^[[:space:]]+/, "", $2)
      print $2
  }')
  read -r ram_total ram_used < <(free -h | awk '/^Mem:/ {print $2, $3}')

  printf '%-18s : %s\n' \
      "Hostname" "$HOSTNAME" \
      "Operating system" "$PRETTY_NAME" \
      "Kernel version" "$kernel" \
      "CPU" "$cpu" \
      "RAM total" "$ram_total" \
      "RAM used" "$ram_used" \
      "Uptime" "$(uptime -p)" \
      "Current user" "$(id -un)"

  printf '\nDisk usage:\n'
  df -h /

  printf '\nIP addresses:\n'
  ip -brief address show up

  printf '\nDefault routes (gateway after "via"):\n'
  ip -4 route show default
  ip -6 route show default
